import { act, cleanup, screen } from '@testing-library/react'

import { CouponCaption } from '~/components/coupons/CouponCaption'
import { AppliedCouponCaptionFragment, CouponFrequency, CurrencyEnum } from '~/generated/graphql'
import { render } from '~/test-utils'

const amountCurrency = CurrencyEnum.Usd

const couponsDataSet = [
  {
    id: 0,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Once,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '0.00% off once',
  },
  {
    id: 1,
    amountCurrency,
    amountCents: 100,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Once,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '$1.00 off once',
  },
  {
    id: 2,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: 100,
    percentageRate: undefined,
    frequency: CouponFrequency.Once,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '0.00% off once',
  },
  {
    id: 3,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: 100,
    frequency: CouponFrequency.Once,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '0.00% off once',
  },
  {
    id: 4,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Recurring,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '0.00% off during undefined period',
  },
  {
    id: 5,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Once,
    frequencyDuration: 2,
    frequencyDurationRemaining: undefined,
    result: '0.00% off once',
  },
  {
    id: 6,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Once,
    frequencyDuration: undefined,
    frequencyDurationRemaining: 3,
    result: '0.00% off once',
  },
  {
    id: 7,
    amountCurrency,
    amountCents: 100,
    amountCentsRemaining: 50,
    percentageRate: undefined,
    frequency: CouponFrequency.Once,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '$0.50 remaining',
  },
  {
    id: 8,
    amountCurrency,
    amountCents: 100,
    amountCentsRemaining: 50,
    percentageRate: undefined,
    frequency: CouponFrequency.Recurring,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '$0.50 off during undefined period',
  },
  {
    id: 9,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Once,
    frequencyDuration: 2,
    frequencyDurationRemaining: 1,
    result: '0.00% off once',
  },
  {
    id: 10,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Recurring,
    frequencyDuration: 2,
    frequencyDurationRemaining: 1,
    result: '0.00% off during 1 period',
  },
  {
    id: 11,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Forever,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '0.00% off forever',
  },
  {
    id: 12,
    amountCurrency,
    amountCents: 100,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Forever,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '$1.00 off forever',
  },
  {
    id: 13,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: 100,
    percentageRate: undefined,
    frequency: CouponFrequency.Forever,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '0.00% off forever',
  },
  {
    id: 14,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: 100,
    frequency: CouponFrequency.Forever,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '100.00% off forever',
  },
  {
    id: 15,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Recurring,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '0.00% off during undefined period',
  },
  {
    id: 16,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Forever,
    frequencyDuration: 2,
    frequencyDurationRemaining: undefined,
    result: '0.00% off forever',
  },
  {
    id: 17,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Forever,
    frequencyDuration: undefined,
    frequencyDurationRemaining: 3,
    result: '0.00% off forever',
  },
  {
    id: 18,
    amountCurrency,
    amountCents: 100,
    amountCentsRemaining: 50,
    percentageRate: undefined,
    frequency: CouponFrequency.Forever,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '$1.00 off forever',
  },
  {
    id: 19,
    amountCurrency,
    amountCents: 100,
    amountCentsRemaining: 50,
    percentageRate: undefined,
    frequency: CouponFrequency.Recurring,
    frequencyDuration: undefined,
    frequencyDurationRemaining: undefined,
    result: '$0.50 off during undefined period',
  },
  {
    id: 20,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Forever,
    frequencyDuration: 2,
    frequencyDurationRemaining: 1,
    result: '0.00% off forever',
  },
  {
    id: 21,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: undefined,
    frequency: CouponFrequency.Recurring,
    frequencyDuration: 2,
    frequencyDurationRemaining: 1,
    result: '0.00% off during 1 period',
  },
  {
    id: 22,
    amountCurrency,
    amountCents: 100,
    amountCentsRemaining: 40,
    percentageRate: undefined,
    frequency: CouponFrequency.Once,
    frequencyDuration: 2,
    frequencyDurationRemaining: 1,
    result: '$0.40 remaining',
  },
  {
    id: 23,
    amountCurrency,
    amountCents: undefined,
    amountCentsRemaining: undefined,
    percentageRate: 1,
    frequency: CouponFrequency.Once,
    frequencyDuration: 2,
    frequencyDurationRemaining: 1,
    result: '1.00% off once',
  },
]

async function prepare(coupon: AppliedCouponCaptionFragment = {} as AppliedCouponCaptionFragment) {
  await act(() => render(<CouponCaption coupon={coupon} />))
}

describe('CouponCaption', () => {
  afterEach(cleanup)

  for (let i = 0; i < couponsDataSet.length; i++) {
    const { id, result, ...dataSet } = couponsDataSet[i]

    it(`renders case ${id}`, async () => {
      await prepare(dataSet as AppliedCouponCaptionFragment)

      expect(screen.getByTestId('coupon-caption')).toHaveTextContent(result)
    })
  }
})
