export const ANALYTICS_INVOICES_FILTER_PREFIX = 'ain'
export const ANALYTICS_USAGE_OVERVIEW_FILTER_PREFIX = 'duo'
export const ANALYTICS_USAGE_BREAKDOWN_FILTER_PREFIX = 'dub'
export const ANALYTICS_USAGE_BREAKDOWN_METERED_FILTER_PREFIX = 'dubm'
export const ANALYTICS_USAGE_BREAKDOWN_RECURRING_FILTER_PREFIX = 'dubr'
export const ANALYTICS_USAGE_BILLABLE_METRIC_FILTER_PREFIX = 'dubm'

export const REVENUE_STREAMS_OVERVIEW_FILTER_PREFIX = 'rs'
export const REVENUE_STREAMS_BREAKDOWN_PLAN_FILTER_PREFIX = 'rsbp'
export const REVENUE_STREAMS_BREAKDOWN_CUSTOMER_FILTER_PREFIX = 'rsbc'

export const MRR_BREAKDOWN_OVERVIEW_FILTER_PREFIX = 'mbo'
export const MRR_BREAKDOWN_PLANS_FILTER_PREFIX = 'mbp'

export const FORECASTS_FILTER_PREFIX = 'for'

export const INVOICE_LIST_FILTER_PREFIX = 'in'

export const CREDIT_NOTE_LIST_FILTER_PREFIX = 'cn'

export const CUSTOMER_LIST_FILTER_PREFIX = 'cu'

export const PREPAID_CREDITS_OVERVIEW_FILTER_PREFIX = 'pc'

export const WEBHOOK_LOGS_FILTER_PREFIX = 'dw'

export const ACTIVITY_LOG_FILTER_PREFIX = 'actl'

export const API_LOGS_FILTER_PREFIX = 'apil'

export const SUBSCRIPTION_LIST_FILTER_PREFIX = 'sub'

export const SECURITY_LOGS_FILTER_PREFIX = 'secul'

export const QUOTE_LIST_FILTER_PREFIX = 'qu'

export const ORDER_FORM_LIST_FILTER_PREFIX = 'of'

export const ORDER_LIST_FILTER_PREFIX = 'or'

export const CUSTOMER_ANALYTICS_FILTER_PREFIX = 'cua'

export const CUSTOMER_INVOICES_DRAFT_FILTER_PREFIX = 'cid'

export const CUSTOMER_INVOICES_FINALIZED_FILTER_PREFIX = 'cif'

export const CUSTOMER_PAYMENTS_FILTER_PREFIX = 'cpa'

export const CUSTOMER_CREDIT_NOTES_FILTER_PREFIX = 'ccn'
