name: Lint

on:
  pull_request:
    types: [opened, reopened, review_requested, ready_for_review, synchronize]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7.0.0

      - name: Install pnpm
        uses: pnpm/action-setup@v6.0.9

      - name: Set up Node.js
        uses: actions/setup-node@v6.4.0
        with:
          node-version-file: package.json
          cache: "pnpm"

      - name: Install Node.js dependencies
        run: pnpm install

      - name: Run code:style check
        run: |
          pnpm run code:style
