import { gql } from '@apollo/client'
import { Icon, tw } from 'lago-design-system'
import { FC, useRef } from 'react'
import { generatePath } from 'react-router-dom'

import { Avatar } from '~/components/designSystem/Avatar'
import { Button } from '~/components/designSystem/Button'
import { Chip } from '~/components/designSystem/Chip'
import { Typography } from '~/components/designSystem/Typography'
import { useCentralizedDialog } from '~/components/dialogs/CentralizedDialog'
import { IntegrationsPage } from '~/components/layouts/Integrations'
import { MainHeader } from '~/components/MainHeader/MainHeader'
import {
  AddLagoTaxManagementDialog,
  AddLagoTaxManagementDialogRef,
} from '~/components/settings/integrations/AddLagoTaxManagementDialog'
import { addToast } from '~/core/apolloClient'
import { CountryCodes } from '~/core/constants/countryCodes'
import { IntegrationsTabsOptionsEnum } from '~/core/constants/tabsOptions'
import { intlFormatNumber } from '~/core/formats/intlFormatNumber'
import { INTEGRATIONS_ROUTE, TAXES_SETTINGS_ROUTE, useNavigate } from '~/core/router'
import {
  useGetBillingEntitiesQuery,
  useGetTaxesForTaxManagementIntegrationDetailsPageQuery,
  useUpdateBillingEntityMutation,
} from '~/generated/graphql'
import { useInternationalization } from '~/hooks/core/useInternationalization'
import { usePermissions } from '~/hooks/usePermissions'
import LagoTaxManagement from '~/public/images/lago-tax-management.svg'

gql`
  query getTaxesForTaxManagementIntegrationDetailsPage {
    taxes(page: 1, limit: 1000, order: "rate", autoGenerated: true) {
      collection {
        id
        code
        name
        rate
      }
    }
  }
`

export const LAGO_TAX_MANAGEMENT_REMOVE_BUTTON_TEST_ID = 'lago-tax-management-remove-button'

const TaxItem: FC<{ name: string; code: string; rate: number }> = ({ name, code, rate }) => {
  const { translate } = useInternationalization()

  return (
    <div className="flex min-h-18 flex-row items-center justify-between gap-3 py-2 shadow-b">
      <div className="flex flex-1 items-center gap-3">
        <Avatar size="big" variant="connector">
          <Icon size="medium" name="percentage" color="dark" />
        </Avatar>
        <div>
          <Typography color="textSecondary" variant="bodyHl" noWrap>
            {name}
          </Typography>
          <Typography variant="caption" noWrap>
            {code}
          </Typography>
        </div>
      </div>
      <Chip className="ml-auto" label={translate('text_657078c28394d6b1ae1b9755')} />
      <Typography variant="body" className="basis-16" color="grey700" align="right">
        {intlFormatNumber(rate / 100, {
          style: 'percent',
        })}
      </Typography>
    </div>
  )
}

const LagoTaxManagementIntegration = () => {
  const navigate = useNavigate()
  const { translate } = useInternationalization()
  const { hasPermissions } = usePermissions()
  const centralizedDialog = useCentralizedDialog()
  const addLagoTaxManagementDialog = useRef<AddLagoTaxManagementDialogRef>(null)

  const { data: billingEntitiesData, loading: billingEntitiesLoading } =
    useGetBillingEntitiesQuery()

  const { data: taxesData, loading: taxesLoading } =
    useGetTaxesForTaxManagementIntegrationDetailsPageQuery()

  const [update] = useUpdateBillingEntityMutation()

  const removeEuTaxManagement = async () => {
    const entities = billingEntitiesData?.billingEntities?.collection || []

    const results = await Promise.all(
      entities.map((billingEntity) => {
        return update({
          variables: {
            input: {
              id: billingEntity.id as string,
              euTaxManagement: false,
            },
          },
        })
      }),
    )

    const hasErrors = results.some((res) => !!res.errors)

    if (hasErrors) return

    navigate(
      generatePath(INTEGRATIONS_ROUTE, {
        integrationGroup: IntegrationsTabsOptionsEnum.Community,
      }),
    )

    addToast({
      message: translate('text_657078c28394d6b1ae1b981d'),
      severity: 'success',
    })
  }

  const loading = billingEntitiesLoading || taxesLoading

  const hasConnectedBillingEntities = billingEntitiesData?.billingEntities?.collection?.find(
    (billingEntity) => billingEntity?.euTaxManagement,
  )

  return (
    <>
      <MainHeader.Configure
        breadcrumb={[
          {
            label: translate('text_62b1edddbf5f461ab9712750'),
            path: generatePath(INTEGRATIONS_ROUTE, {
              integrationGroup: IntegrationsTabsOptionsEnum.Community,
            }),
          },
        ]}
        entity={{
          viewName: translate('text_657078c28394d6b1ae1b9713'),
          viewNameLoading: loading,
          metadata: translate('text_657078c28394d6b1ae1b971f'),
          metadataLoading: loading,
          badges: hasConnectedBillingEntities
            ? [{ type: 'default', label: translate('text_62b1edddbf5f461ab97127ad') }]
            : [],
          icon: <LagoTaxManagement />,
        }}
        actions={{
          items: [
            {
              type: 'action',
              label: translate('text_657078c28394d6b1ae1b971b'),
              variant: 'secondary',
              hidden: !hasPermissions(['billingEntitiesUpdate']),
              disabled: loading,
              dataTest: LAGO_TAX_MANAGEMENT_REMOVE_BUTTON_TEST_ID,
              onClick: () => {
                centralizedDialog.open({
                  title: translate('text_657078c28394d6b1ae1b9707'),
                  description: translate('text_657078c28394d6b1ae1b970d'),
                  actionText: translate('text_657078c28394d6b1ae1b971b'),
                  colorVariant: 'danger',
                  onAction: removeEuTaxManagement,
                })
              },
            },
          ],
          loading,
        }}
      />

      <IntegrationsPage.Container>
        <section>
          <IntegrationsPage.Headline
            label={translate('text_657078c28394d6b1ae1b9725')}
            description={translate('text_1746697495328feu6uz9q6oo')}
          >
            <Button
              variant="inline"
              onClick={() => {
                addLagoTaxManagementDialog.current?.openDialog()
              }}
            >
              {translate('text_174669693169993cmj3546tp')}
            </Button>
          </IntegrationsPage.Headline>

          {loading && <IntegrationsPage.ItemSkeleton />}

          {!loading && (
            <>
              <div className="flex items-center justify-between py-3 shadow-b">
                <Typography variant="bodyHl" color="grey600">
                  {translate('text_17430772961896bgqutmnx7g')}
                </Typography>

                <Typography variant="bodyHl" color="grey600">
                  {translate('text_62ab2d0396dd6b0361614da0')}
                </Typography>
              </div>

              {billingEntitiesData?.billingEntities?.collection
                ?.filter((billingEntity) => billingEntity.euTaxManagement === true)
                .map((billingEntity, index) => (
                  <div
                    className={tw('flex items-center justify-between py-3', {
                      'shadow-b':
                        index !== billingEntitiesData?.billingEntities?.collection?.length - 1,
                    })}
                    key={`lago-tax-management-${billingEntity.id}`}
                  >
                    <div className="flex items-center gap-3">
                      <Icon name="company" size="small" />

                      <Typography variant="body" color="grey700">
                        {billingEntity?.name || billingEntity?.code}
                      </Typography>
                    </div>

                    <Typography variant="body" color="grey700">
                      {billingEntity?.country && CountryCodes[billingEntity?.country]}
                    </Typography>
                  </div>
                ))}
            </>
          )}
        </section>

        <section>
          <IntegrationsPage.Headline label={translate('text_657078c28394d6b1ae1b9743')}>
            {hasPermissions(['billingEntitiesView']) && (
              <Button
                variant="inline"
                disabled={loading}
                onClick={() => {
                  navigate(TAXES_SETTINGS_ROUTE)
                }}
              >
                {translate('text_657078c28394d6b1ae1b973d')}
              </Button>
            )}
          </IntegrationsPage.Headline>

          {loading && <IntegrationsPage.ItemSkeleton />}
          {!loading &&
            taxesData?.taxes?.collection.map((tax) => (
              <TaxItem key={tax.id} name={tax.name} code={tax.code} rate={tax.rate} />
            ))}
        </section>
      </IntegrationsPage.Container>

      <AddLagoTaxManagementDialog isUpdate={true} ref={addLagoTaxManagementDialog} />
    </>
  )
}

export default LagoTaxManagementIntegration
