apiVersion: 1

datasources:
  - name: LagoPostgres
    uid: lagopg
    type: grafana-postgresql-datasource
    access: proxy
    url: db:5432
    database: lago
    user: lago
    isDefault: false
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
      maxOpenConns: 5
      maxIdleConns: 2
    secureJsonData:
      password: changeme
