apiVersion: 1

datasources:
  - name: RisingWave
    uid: risingwave
    type: grafana-postgresql-datasource
    access: proxy
    url: risingwave:4566
    database: dev
    user: root
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1300
      timescaledb: false
      maxOpenConns: 5
      maxIdleConns: 2
    secureJsonData:
      password: ""
