apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lago.fullname" . }}-env
  labels:
    {{- include "lago.labels" . | nindent 4 }}
data:
  LAGO_API_URL: "https://{{ .Values.domain }}/api"
  LAGO_FRONT_URL: "https://{{ .Values.domain }}"
  LAGO_PDF_URL: "http://{{ include "lago.fullname" . }}-pdf:{{ .Values.pdf.port }}"
  API_URL: "https://{{ .Values.domain }}"
  APP_ENV: "production"
  {{- range $k, $v := .Values.env }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
