apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lago.fullname" . }}-front
  labels:
    {{- include "lago.labels" . | nindent 4 }}
    app.kubernetes.io/component: front
spec:
  replicas: {{ .Values.front.replicas }}
  selector:
    matchLabels:
      {{- include "lago.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: front
  template:
    metadata:
      labels:
        {{- include "lago.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: front
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: front
          image: {{ include "lago.image.front" . | quote }}
          imagePullPolicy: {{ .Values.image.front.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.front.port }}
          env:
            - name: API_URL
              value: "https://{{ .Values.domain }}"
            - name: APP_ENV
              value: "production"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.front.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lago.fullname" . }}-front
  labels:
    {{- include "lago.labels" . | nindent 4 }}
    app.kubernetes.io/component: front
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.front.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "lago.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: front
