import { gql } from '@apollo/client'
import { Icon } from 'lago-design-system'
import { useMemo, useRef } from 'react'

import { useDeleteCustomerDocumentLocaleDialog } from '~/components/customers/DeleteCustomerDocumentLocaleDialog'
import {
  DeleteCustomerFinalizeZeroAmountInvoiceDialog,
  DeleteCustomerFinalizeZeroAmountInvoiceDialogRef,
} from '~/components/customers/DeleteCustomerFinalizeZeroAmountInvoiceDialog'
import {
  DeleteCustomerGracePeriodeDialog,
  DeleteCustomerGracePeriodeDialogRef,
} from '~/components/customers/DeleteCustomerGracePeriodeDialog'
import {
  DeleteOrganizationNetPaymentTermDialog,
  DeleteOrganizationNetPaymentTermDialogRef,
} from '~/components/customers/DeleteCustomerNetPaymentTermDialog'
import { useDeleteCustomerVatRateDialog } from '~/components/customers/DeleteCustomerVatRateDialog'
import { useEditCustomerDocumentLocaleDialog } from '~/components/customers/EditCustomerDocumentLocaleDialog'
import {
  EditCustomerDunningCampaignDialog,
  EditCustomerDunningCampaignDialogRef,
} from '~/components/customers/EditCustomerDunningCampaignDialog'
import {
  EditCustomerInvoiceCustomSectionsDialog,
  EditCustomerInvoiceCustomSectionsDialogRef,
} from '~/components/customers/EditCustomerInvoiceCustomSectionsDialog'
import {
  EditCustomerInvoiceGracePeriodDialog,
  EditCustomerInvoiceGracePeriodDialogRef,
} from '~/components/customers/EditCustomerInvoiceGracePeriodDialog'
import {
  EditCustomerVatRateDialog,
  EditCustomerVatRateDialogRef,
} from '~/components/customers/EditCustomerVatRateDialog'
import {
  EditCustomerIssuingDatePolicyDialog,
  EditCustomerIssuingDatePolicyDialogRef,
} from '~/components/customers/settings/EditCustomerIssuingDatePolicyDialog'
import { Avatar } from '~/components/designSystem/Avatar'
import { Button } from '~/components/designSystem/Button'
import { Chip } from '~/components/designSystem/Chip'
import { GenericPlaceholder } from '~/components/designSystem/GenericPlaceholder'
import { Popper } from '~/components/designSystem/Popper'
import { Table, TableColumn } from '~/components/designSystem/Table/Table'
import { Tooltip } from '~/components/designSystem/Tooltip'
import { Typography } from '~/components/designSystem/Typography'
import { usePremiumWarningDialog } from '~/components/dialogs/PremiumWarningDialog'
import {
  SettingsListItem,
  SettingsListItemHeader,
  SettingsListItemLoadingSkeleton,
  SettingsListWrapper,
  SettingsPaddedContainer,
} from '~/components/layouts/Settings'
import {
  EditFinalizeZeroAmountInvoiceDialog,
  EditFinalizeZeroAmountInvoiceDialogRef,
} from '~/components/settings/invoices/EditFinalizeZeroAmountInvoiceDialog'
import {
  EditNetPaymentTermDialog,
  EditNetPaymentTermDialogRef,
} from '~/components/settings/invoices/EditNetPaymentTermDialog'
import {
  INVOICE_ISSUING_DATE_ADJUSTMENT_SETTING_KEYS,
  INVOICE_ISSUING_DATE_ANCHOR_SETTING_KEYS,
} from '~/core/constants/issuingDatePolicy'
import { intlFormatNumber } from '~/core/formats/intlFormatNumber'
import { DocumentLocales } from '~/core/translations/documentLocales'
import {
  BillingEntitySubscriptionInvoiceIssuingDateAdjustmentEnum,
  BillingEntitySubscriptionInvoiceIssuingDateAnchorEnum,
  CustomerForDeleteVatRateDialogFragmentDoc,
  CustomerSubscriptionInvoiceIssuingDateAdjustmentEnum,
  CustomerSubscriptionInvoiceIssuingDateAnchorEnum,
  DeleteCustomerDocumentLocaleFragmentDoc,
  DeleteCustomerGracePeriodFragmentDoc,
  DeleteCustomerNetPaymentTermFragmentDoc,
  EditCustomerDocumentLocaleFragmentDoc,
  EditCustomerDunningCampaignFragmentDoc,
  EditCustomerInvoiceCustomSectionFragmentDoc,
  EditCustomerInvoiceGracePeriodFragmentDoc,
  EditCustomerIssuingDatePolicyDialogFragmentDoc,
  EditCustomerVatRateFragmentDoc,
  FinalizeZeroAmountInvoiceEnum,
  PremiumIntegrationTypeEnum,
  useGetCustomerSettingsQuery,
} from '~/generated/graphql'
import { useInternationalization } from '~/hooks/core/useInternationalization'
import { useCurrentUser } from '~/hooks/useCurrentUser'
import { useOrganizationInfos } from '~/hooks/useOrganizationInfos'
import { usePermissions } from '~/hooks/usePermissions'
import ErrorImage from '~/public/images/maneki/error.svg'
import { MenuPopper } from '~/styles'
import { tw } from '~/styles/utils'

gql`
  fragment CustomerAppliedTaxRatesForSettings on Customer {
    id
    taxes {
      id
      name
      code
      rate
      autoGenerated
    }
  }

  fragment CustomerAppliedDunningCampaignForSettings on Customer {
    currency
    appliedDunningCampaign {
      id
      appliedToOrganization
      code
      name
      thresholds {
        currency
      }
    }
    excludeFromDunningCampaign
  }

  fragment CustomerAppliedInvoiceCustomSections on Customer {
    configurableInvoiceCustomSections {
      id
      name
      code
    }
    skipInvoiceCustomSections
  }

  query getCustomerSettings($id: ID!) {
    customer(id: $id) {
      id
      invoiceGracePeriod
      netPaymentTerm
      finalizeZeroAmountInvoice

      billingEntity {
        id
        netPaymentTerm
        finalizeZeroAmountInvoice
        billingConfiguration {
          id
          invoiceGracePeriod
          documentLocale
          subscriptionInvoiceIssuingDateAdjustment
          subscriptionInvoiceIssuingDateAnchor
        }
        appliedDunningCampaign {
          id
          name
          code
          appliedToOrganization
          thresholds {
            currency
          }
        }
      }

      billingConfiguration {
        id
        documentLocale
        subscriptionInvoiceIssuingDateAdjustment
        subscriptionInvoiceIssuingDateAnchor
      }

      ...CustomerAppliedTaxRatesForSettings
      ...CustomerAppliedDunningCampaignForSettings
      ...CustomerAppliedInvoiceCustomSections
      ...EditCustomerInvoiceCustomSection
      ...EditCustomerVatRate
      ...EditCustomerDocumentLocale
      ...EditCustomerDunningCampaign
      ...EditCustomerInvoiceGracePeriod
      ...DeleteCustomerGracePeriod
      ...DeleteCustomerDocumentLocale
      ...CustomerForDeleteVatRateDialog
      ...DeleteCustomerNetPaymentTerm
      ...EditCustomerIssuingDatePolicyDialog
    }
  }

  ${EditCustomerVatRateFragmentDoc}
  ${EditCustomerInvoiceGracePeriodFragmentDoc}
  ${EditCustomerDocumentLocaleFragmentDoc}
  ${EditCustomerDunningCampaignFragmentDoc}
  ${EditCustomerInvoiceCustomSectionFragmentDoc}
  ${DeleteCustomerGracePeriodFragmentDoc}
  ${DeleteCustomerDocumentLocaleFragmentDoc}
  ${CustomerForDeleteVatRateDialogFragmentDoc}
  ${DeleteCustomerNetPaymentTermFragmentDoc}
  ${EditCustomerIssuingDatePolicyDialogFragmentDoc}
`

interface CustomerSettingsProps {
  customerId: string
}

export const CustomerSettings = ({ customerId }: CustomerSettingsProps) => {
  const { translate } = useInternationalization()
  const { isPremium } = useCurrentUser()
  const { hasPermissions } = usePermissions()
  const { organization: { premiumIntegrations } = {} } = useOrganizationInfos()
  const { data, loading, error } = useGetCustomerSettingsQuery({
    variables: { id: customerId as string },
    skip: !customerId,
  })
  const customer = data?.customer
  const billingEntity = data?.customer?.billingEntity
  const editVATDialogRef = useRef<EditCustomerVatRateDialogRef>(null)
  const editIssuingDatePolicyDialogRef = useRef<EditCustomerIssuingDatePolicyDialogRef>(null)
  const { openDeleteCustomerVatRateDialog } = useDeleteCustomerVatRateDialog()
  const editInvoiceGracePeriodDialogRef = useRef<EditCustomerInvoiceGracePeriodDialogRef>(null)
  const deleteGracePeriodDialogRef = useRef<DeleteCustomerGracePeriodeDialogRef>(null)
  const { openEditCustomerDocumentLocaleDialog } = useEditCustomerDocumentLocaleDialog()
  const editCustomerDunningCampaignDialogRef = useRef<EditCustomerDunningCampaignDialogRef>(null)
  const editCustomerInvoiceCustomSectionsDialogRef =
    useRef<EditCustomerInvoiceCustomSectionsDialogRef>(null)
  const { openDeleteCustomerDocumentLocaleDialog } = useDeleteCustomerDocumentLocaleDialog()
  const { open: openPremiumWarningDialog } = usePremiumWarningDialog()
  const editNetPaymentTermDialogRef = useRef<EditNetPaymentTermDialogRef>(null)
  const deleteOrganizationNetPaymentTermDialogRef =
    useRef<DeleteOrganizationNetPaymentTermDialogRef>(null)
  const editFinalizeZeroAmountInvoiceDialogRef =
    useRef<EditFinalizeZeroAmountInvoiceDialogRef>(null)
  const deleteCustomerFinalizeZeroAmountInvoiceDialogRef =
    useRef<DeleteCustomerFinalizeZeroAmountInvoiceDialogRef>(null)

  const { issuingDateAnchorSettingCopy, issuingDateAdjustmentSettingCopy } = useMemo(() => {
    const hasUserDefinedAnchor =
      !!customer?.billingConfiguration?.subscriptionInvoiceIssuingDateAnchor
    const hasUserDefinedAdjustment =
      !!customer?.billingConfiguration?.subscriptionInvoiceIssuingDateAdjustment

    const inheritCopy = translate('text_1763407743132k0lsbmuh6a1')

    const customerAnchorCopy = translate(
      INVOICE_ISSUING_DATE_ANCHOR_SETTING_KEYS[
        customer?.billingConfiguration?.subscriptionInvoiceIssuingDateAnchor ||
          CustomerSubscriptionInvoiceIssuingDateAnchorEnum.NextPeriodStart
      ],
    )

    const billingEntityAnchorCopy = translate(
      INVOICE_ISSUING_DATE_ANCHOR_SETTING_KEYS[
        customer?.billingEntity?.billingConfiguration?.subscriptionInvoiceIssuingDateAnchor ||
          BillingEntitySubscriptionInvoiceIssuingDateAnchorEnum.NextPeriodStart
      ],
    )

    const billingEntityAdjustmentCopy = translate(
      INVOICE_ISSUING_DATE_ADJUSTMENT_SETTING_KEYS[
        customer?.billingEntity?.billingConfiguration?.subscriptionInvoiceIssuingDateAdjustment ||
          BillingEntitySubscriptionInvoiceIssuingDateAdjustmentEnum.AlignWithFinalizationDate
      ],
    )

    const customerAdjustmentCopy = translate(
      INVOICE_ISSUING_DATE_ADJUSTMENT_SETTING_KEYS[
        customer?.billingConfiguration?.subscriptionInvoiceIssuingDateAdjustment ||
          CustomerSubscriptionInvoiceIssuingDateAdjustmentEnum.AlignWithFinalizationDate
      ],
    )

    return {
      issuingDateAnchorSettingCopy: hasUserDefinedAnchor
        ? customerAnchorCopy
        : `${billingEntityAnchorCopy} ${inheritCopy}`,
      issuingDateAdjustmentSettingCopy: hasUserDefinedAdjustment
        ? customerAdjustmentCopy
        : `${billingEntityAdjustmentCopy} ${inheritCopy}`,
    }
  }, [
    customer?.billingConfiguration?.subscriptionInvoiceIssuingDateAdjustment,
    customer?.billingConfiguration?.subscriptionInvoiceIssuingDateAnchor,
    customer?.billingEntity?.billingConfiguration?.subscriptionInvoiceIssuingDateAdjustment,
    customer?.billingEntity?.billingConfiguration?.subscriptionInvoiceIssuingDateAnchor,
    translate,
  ])

  if (!!error && !loading) {
    return (
      <GenericPlaceholder
        title={translate('text_62c3f3fca8a1625624e83379')}
        subtitle={translate('text_62c3f3fca8a1625624e8337e')}
        buttonTitle={translate('text_62c3f3fca8a1625624e83382')}
        buttonVariant="primary"
        buttonAction={() => location.reload()}
        image={<ErrorImage width="136" height="104" />}
      />
    )
  }

  const hasAutoDunningIntegration = premiumIntegrations?.includes(
    PremiumIntegrationTypeEnum.AutoDunning,
  )
  const dunningCampaign =
    customer?.appliedDunningCampaign ?? billingEntity?.appliedDunningCampaign ?? undefined

  const isDunningCampaignApplicable =
    !!dunningCampaign &&
    !!dunningCampaign?.thresholds?.some((threshold) => threshold.currency === customer?.currency)

  const isInvoiceCustomSectionConfigurable = !!customer?.configurableInvoiceCustomSections?.length

  function getNetPaymentTermCopy(
    customerNetPaymentTerm: number | null | undefined,
    billingEntityNetPaymentTerm: number,
  ): string {
    const isCustomerNetPaymentTermDefined = typeof customerNetPaymentTerm === 'number'

    if (!isCustomerNetPaymentTermDefined) {
      return translate(
        'text_64c7a89b6c67eb6c98898241',
        {
          days: billingEntityNetPaymentTerm ?? 0,
        },
        billingEntityNetPaymentTerm ?? 0,
      )
    }

    if (customerNetPaymentTerm === 0) {
      return translate('text_64c7a89b6c67eb6c98898125')
    }

    return translate(
      'text_64c7a89b6c67eb6c9889815f',
      {
        days: customerNetPaymentTerm,
      },
      customerNetPaymentTerm,
    )
  }

  function getDunningCampaignContent(): React.ReactNode {
    if (!dunningCampaign || customer?.excludeFromDunningCampaign) {
      return (
        <Typography variant="body" color="grey700">
          {translate('text_1729541149109r8u8nlsu75e')}
        </Typography>
      )
    }

    if (!isDunningCampaignApplicable) {
      return (
        <Typography variant="body" color="grey700">
          {translate('text_17295411491091t7ii66l5ex')}
        </Typography>
      )
    }

    return (
      <Table
        name="customer-dunnings-settings"
        containerSize={{ default: 0 }}
        rowSize={72}
        isLoading={loading}
        data={[dunningCampaign]}
        columns={[
          {
            key: 'name',
            title: translate('text_1729542024833rpf3nsekh42'),
            maxSpace: true,
            content: ({ name, code }) => (
              <div className="flex flex-1 items-center gap-3" data-test={code}>
                <Avatar size="big" variant="connector">
                  <Icon size="medium" name="coin-dollar" color="dark" />
                </Avatar>
                <div>
                  <Typography color="textSecondary" variant="bodyHl" noWrap>
                    {name}
                  </Typography>
                  <Typography variant="caption" noWrap>
                    {code}
                  </Typography>
                </div>
              </div>
            ),
          },
          ...(!customer?.appliedDunningCampaign
            ? [
                {
                  key: 'appliedToOrganization',
                  title: translate('text_63ac86d797f728a87b2f9fa7'),
                  content: () => <Chip label={translate('text_1729542098338prhjz7s29kt')} />,
                } as TableColumn<{
                  appliedToOrganization: boolean
                }>,
              ]
            : []),
        ]}
      />
    )
  }

  return (
    <>
      <SettingsPaddedContainer className="max-w-full p-0 md:px-0">
        <SettingsListWrapper>
          {!!loading ? (
            <SettingsListItemLoadingSkeleton count={2} />
          ) : (
            <>
              {/* Document language */}
              <SettingsListItem>
                <SettingsListItemHeader
                  label={translate('text_63e51ef4985f0ebd75c212fd')}
                  sublabel={translate('text_1728031300577ipb2cxnths3')}
                  action={
                    hasPermissions(['customersUpdate']) ? (
                      <>
                        {typeof customer?.billingConfiguration?.documentLocale !== 'string' ? (
                          <Button
                            disabled={loading}
                            variant="inline"
                            endIcon={isPremium ? undefined : 'sparkles'}
                            onClick={() =>
                              isPremium
                                ? customer && openEditCustomerDocumentLocaleDialog(customer)
                                : openPremiumWarningDialog()
                            }
                          >
                            {translate('text_645bb193927b375079d28ad2')}
                          </Button>
                        ) : (
                          <Popper
                            PopperProps={{ placement: 'bottom-end' }}
                            opener={
                              <Button
                                disabled={loading}
                                icon="dots-horizontal"
                                variant="quaternary"
                              />
                            }
                          >
                            {({ closePopper }) => (
                              <MenuPopper>
                                <Button
                                  disabled={loading}
                                  startIcon="pen"
                                  variant="quaternary"
                                  align="left"
                                  onClick={() => {
                                    if (customer) {
                                      openEditCustomerDocumentLocaleDialog(customer)
                                    }
                                    closePopper()
                                  }}
                                >
                                  {translate('text_63ea0f84f400488553caa785')}
                                </Button>
                                <Button
                                  disabled={loading}
                                  startIcon="trash"
                                  variant="quaternary"
                                  align="left"
                                  onClick={() => {
                                    if (customer) {
                                      openDeleteCustomerDocumentLocaleDialog(customer)
                                    }
                                    closePopper()
                                  }}
                                >
                                  {translate('text_63ea0f84f400488553caa786')}
                                </Button>
                              </MenuPopper>
                            )}
                          </Popper>
                        )}
                      </>
                    ) : undefined
                  }
                />

                <Typography variant="body" color="grey700">
                  {!!customer?.billingConfiguration?.documentLocale
                    ? DocumentLocales[
                        customer?.billingConfiguration
                          ?.documentLocale as keyof typeof DocumentLocales
                      ]
                    : translate('text_1728374331992d2alok9y3kr', {
                        value:
                          DocumentLocales[
                            (billingEntity?.billingConfiguration?.documentLocale ||
                              'en') as keyof typeof DocumentLocales
                          ],
                      })}
                </Typography>
              </SettingsListItem>

              {/* Dunnings campaign */}
              {hasAutoDunningIntegration && (
                <SettingsListItem
                  className={tw(
                    isDunningCampaignApplicable &&
                      !customer?.excludeFromDunningCampaign &&
                      'shadow-inherit',
                  )}
                >
                  <SettingsListItemHeader
                    label={translate('text_1728584028187fg2ebhssz6r')}
                    sublabel={translate('text_1729541146351qyno3mh09gi')}
                    action={
                      <Button
                        disabled={loading}
                        variant="inline"
                        onClick={() => editCustomerDunningCampaignDialogRef?.current?.openDialog()}
                      >
                        {translate('text_63e51ef4985f0ebd75c212fc')}
                      </Button>
                    }
                  />

                  {getDunningCampaignContent()}
                </SettingsListItem>
              )}

              {/* Finalize empty invoice setting */}
              <SettingsListItem>
                <SettingsListItemHeader
                  label={translate('text_1725549671287r9tnu5cuoeu')}
                  sublabel={translate('text_1725538340200495slgen6ji')}
                  action={
                    customer?.finalizeZeroAmountInvoice ===
                    FinalizeZeroAmountInvoiceEnum.Inherit ? (
                      <Button
                        disabled={loading}
                        variant="inline"
                        onClick={() =>
                          editFinalizeZeroAmountInvoiceDialogRef?.current?.openDialog()
                        }
                      >
                        {translate('text_645bb193927b375079d28ad2')}
                      </Button>
                    ) : (
                      <Popper
                        PopperProps={{ placement: 'bottom-end' }}
                        opener={
                          <Button disabled={loading} icon="dots-horizontal" variant="quaternary" />
                        }
                      >
                        {({ closePopper }) => (
                          <MenuPopper>
                            <Button
                              disabled={loading}
                              startIcon="pen"
                              variant="quaternary"
                              align="left"
                              onClick={() => {
                                editFinalizeZeroAmountInvoiceDialogRef?.current?.openDialog()
                                closePopper()
                              }}
                            >
                              {translate('text_63aa15caab5b16980b21b0b8')}
                            </Button>
                            <Button
                              disabled={loading}
                              startIcon="trash"
                              variant="quaternary"
                              align="left"
                              onClick={() => {
                                deleteCustomerFinalizeZeroAmountInvoiceDialogRef?.current?.openDialog()
                                closePopper()
                              }}
                            >
                              {translate('text_63aa15caab5b16980b21b0ba')}
                            </Button>
                          </MenuPopper>
                        )}
                      </Popper>
                    )
                  }
                />

                <Typography variant="body" color="grey700">
                  {customer?.finalizeZeroAmountInvoice === FinalizeZeroAmountInvoiceEnum.Inherit ? (
                    <>
                      {billingEntity?.finalizeZeroAmountInvoice
                        ? translate('text_1725549671287ancbf00edxx')
                        : translate('text_1725549671288zkq9sr0y46l')}
                      {` ${translate('text_17255500892009uqfqttms4w')}`}
                    </>
                  ) : (
                    <>
                      {customer?.finalizeZeroAmountInvoice ===
                      FinalizeZeroAmountInvoiceEnum.Finalize
                        ? translate('text_1725549671287ancbf00edxx')
                        : translate('text_1725549671288zkq9sr0y46l')}
                    </>
                  )}
                </Typography>
              </SettingsListItem>

              {/* Grace period */}
              <SettingsListItem>
                <SettingsListItemHeader
                  label={translate('text_638dc196fb209d551f3d8141')}
                  sublabel={translate('text_1728031300577ozl3dbfygr7')}
                  action={
                    hasPermissions(['customersUpdate']) ? (
                      <>
                        {typeof customer?.invoiceGracePeriod !== 'number' ? (
                          <Button
                            disabled={loading}
                            variant="inline"
                            endIcon={isPremium ? undefined : 'sparkles'}
                            onClick={() =>
                              isPremium
                                ? editInvoiceGracePeriodDialogRef?.current?.openDialog()
                                : openPremiumWarningDialog()
                            }
                          >
                            {translate('text_645bb193927b375079d28ad2')}
                          </Button>
                        ) : (
                          <Popper
                            PopperProps={{ placement: 'bottom-end' }}
                            opener={
                              <Button
                                disabled={loading}
                                icon="dots-horizontal"
                                variant="quaternary"
                              />
                            }
                          >
                            {({ closePopper }) => (
                              <MenuPopper>
                                <Button
                                  disabled={loading}
                                  startIcon="pen"
                                  variant="quaternary"
                                  align="left"
                                  onClick={() => {
                                    editInvoiceGracePeriodDialogRef.current?.openDialog()
                                    closePopper()
                                  }}
                                >
                                  {translate('text_63aa15caab5b16980b21b0b8')}
                                </Button>
                                <Button
                                  disabled={loading}
                                  startIcon="trash"
                                  variant="quaternary"
                                  align="left"
                                  onClick={() => {
                                    deleteGracePeriodDialogRef.current?.openDialog()
                                    closePopper()
                                  }}
                                >
                                  {translate('text_63aa15caab5b16980b21b0ba')}
                                </Button>
                              </MenuPopper>
                            )}
                          </Popper>
                        )}
                      </>
                    ) : undefined
                  }
                />

                <Typography variant="body" color="grey700">
                  {typeof customer?.invoiceGracePeriod === 'number'
                    ? translate(
                        'text_638dff9779fb99299bee9132',
                        {
                          invoiceGracePeriod: customer?.invoiceGracePeriod,
                        },
                        customer?.invoiceGracePeriod,
                      )
                    : translate(
                        'text_63aa085d28b8510cd464440d',
                        {
                          invoiceGracePeriod:
                            billingEntity?.billingConfiguration?.invoiceGracePeriod || 0,
                        },
                        billingEntity?.billingConfiguration?.invoiceGracePeriod || 0,
                      )}
                </Typography>
              </SettingsListItem>

              {/* Invoice custom section */}
              <SettingsListItem
                className={tw(
                  isInvoiceCustomSectionConfigurable &&
                    !customer.skipInvoiceCustomSections &&
                    'shadow-inherit',
                )}
              >
                <SettingsListItemHeader
                  label={translate('text_1732553358445168zt8fopyf')}
                  sublabel={translate('text_1732553358445p7rg0i0dzws')}
                  action={
                    hasPermissions(['customersUpdate']) ? (
                      <Button
                        disabled={loading}
                        variant="inline"
                        endIcon={isPremium ? undefined : 'sparkles'}
                        onClick={() =>
                          editCustomerInvoiceCustomSectionsDialogRef?.current?.openDialog()
                        }
                      >
                        {translate('text_63e51ef4985f0ebd75c212fc')}
                      </Button>
                    ) : undefined
                  }
                />

                {customer?.skipInvoiceCustomSections && (
                  <Typography variant="body" color="grey700">
                    {translate('text_1735223938916tlygbi5v0nd')}
                  </Typography>
                )}
                {!customer?.skipInvoiceCustomSections && isInvoiceCustomSectionConfigurable && (
                  <Table
                    name="customer-custom-sections-settings"
                    containerSize={{ default: 0 }}
                    rowSize={48}
                    isLoading={loading}
                    data={customer.configurableInvoiceCustomSections || []}
                    columns={[
                      {
                        key: 'name',
                        title: translate('text_6419c64eace749372fc72b0f'),
                        maxSpace: true,
                        content: ({ name }) => (
                          <Typography color="textSecondary" noWrap>
                            {name}
                          </Typography>
                        ),
                      },
                    ]}
                  />
                )}
                {!customer?.skipInvoiceCustomSections && !isInvoiceCustomSectionConfigurable && (
                  <Typography variant="body" color="grey700">
                    {translate('text_1735223938916wjmtgs2juy4')}
                  </Typography>
                )}
              </SettingsListItem>

              {/* Net payment term */}
              <SettingsListItem>
                <SettingsListItemHeader
                  label={translate('text_64c7a89b6c67eb6c98898167')}
                  sublabel={translate('text_1728031300577aivplw3hqav')}
                  action={
                    hasPermissions(['customersUpdate']) ? (
                      <>
                        {typeof customer?.netPaymentTerm !== 'number' ? (
                          <Button
                            disabled={loading}
                            variant="inline"
                            onClick={() =>
                              editNetPaymentTermDialogRef?.current?.openDialog(customer)
                            }
                          >
                            {translate('text_645bb193927b375079d28ad2')}
                          </Button>
                        ) : (
                          <Popper
                            PopperProps={{ placement: 'bottom-end' }}
                            opener={
                              <Button
                                disabled={loading}
                                icon="dots-horizontal"
                                variant="quaternary"
                              />
                            }
                          >
                            {({ closePopper }) => (
                              <MenuPopper>
                                <Button
                                  disabled={loading}
                                  startIcon="pen"
                                  variant="quaternary"
                                  align="left"
                                  onClick={() => {
                                    editNetPaymentTermDialogRef?.current?.openDialog(customer)
                                    closePopper()
                                  }}
                                >
                                  {translate('text_63aa15caab5b16980b21b0b8')}
                                </Button>
                                <Button
                                  disabled={loading}
                                  startIcon="trash"
                                  variant="quaternary"
                                  align="left"
                                  onClick={() => {
                                    deleteOrganizationNetPaymentTermDialogRef?.current?.openDialog()
                                    closePopper()
                                  }}
                                >
                                  {translate('text_63aa15caab5b16980b21b0ba')}
                                </Button>
                              </MenuPopper>
                            )}
                          </Popper>
                        )}
                      </>
                    ) : undefined
                  }
                />

                <Typography variant="body" color="grey700">
                  {getNetPaymentTermCopy(
                    customer?.netPaymentTerm,
                    billingEntity?.netPaymentTerm || 0,
                  )}
                </Typography>
              </SettingsListItem>

              {/* Issuing date policy */}
              <SettingsListItem>
                <SettingsListItemHeader
                  label={translate('text_1763407530093r6zuzwr3x7p')}
                  sublabel={translate('text_1763414803053xz3x7xjr3jf')}
                  action={
                    hasPermissions(['customersUpdate']) ? (
                      <Button
                        variant="inline"
                        disabled={loading}
                        onClick={() => editIssuingDatePolicyDialogRef?.current?.openDialog()}
                        data-test="add-issuing-date-policy-button"
                      >
                        {translate('text_645bb193927b375079d28ad2')}
                      </Button>
                    ) : undefined
                  }
                />

                <div className="flex items-baseline gap-1">
                  <Typography variant="body" color="grey700">
                    <div>{issuingDateAnchorSettingCopy}</div>
                    <div>{issuingDateAdjustmentSettingCopy}</div>
                  </Typography>
                </div>
              </SettingsListItem>

              {/* Tax */}
              <SettingsListItem>
                <SettingsListItemHeader
                  label={translate('text_637f819eff19cd55a56d55e6')}
                  sublabel={translate('text_1728031300577obxo6934yo7')}
                  action={
                    hasPermissions(['customersUpdate']) ? (
                      <Button
                        variant="inline"
                        disabled={loading}
                        onClick={() => editVATDialogRef?.current?.openDialog()}
                        data-test="add-vat-rate-button"
                      >
                        {translate('text_645bb193927b375079d28ad2')}
                      </Button>
                    ) : undefined
                  }
                />

                {!customer?.taxes?.length ? (
                  <Typography variant="body" color="grey700">
                    {translate('text_64639f5e63a5cc0076779db7')}
                  </Typography>
                ) : (
                  <Table
                    name="invoice-settings-taxes"
                    containerSize={{ default: 0 }}
                    rowSize={72}
                    data={customer?.taxes}
                    columns={[
                      {
                        key: 'name',
                        title: translate('text_17280312664187sb64qzmyhy'),
                        maxSpace: true,
                        content: ({ name, code }) => (
                          <div className="flex flex-1 items-center gap-3">
                            <Avatar size="big" variant="connector">
                              <Icon size="medium" name="percentage" color="dark" />
                            </Avatar>
                            <div>
                              <Typography color="textSecondary" variant="bodyHl" noWrap>
                                {name}
                              </Typography>
                              <Typography variant="caption" noWrap>
                                {code}
                              </Typography>
                            </div>
                          </div>
                        ),
                      },
                      {
                        key: 'rate',
                        textAlign: 'right',
                        title: translate('text_64de472463e2da6b31737de0'),
                        content: ({ rate }) => (
                          <Typography variant="body" color="grey700">
                            {intlFormatNumber((rate || 0) / 100, {
                              style: 'percent',
                            })}
                          </Typography>
                        ),
                      },
                    ]}
                    actionColumn={
                      hasPermissions(['customersUpdate'])
                        ? (row) => {
                            return (
                              <Tooltip
                                placement="top-end"
                                title={translate(
                                  row.autoGenerated
                                    ? 'text_175994876500346yy1p0qefd'
                                    : 'text_64639cfe2e46e9007d11b49d',
                                )}
                              >
                                <Button
                                  icon="trash"
                                  variant="quaternary"
                                  disabled={row.autoGenerated}
                                  onClick={() => {
                                    if (customer) {
                                      openDeleteCustomerVatRateDialog({
                                        customer,
                                        taxRate: row,
                                      })
                                    }
                                  }}
                                />
                              </Tooltip>
                            )
                          }
                        : undefined
                    }
                  />
                )}
              </SettingsListItem>
            </>
          )}
        </SettingsListWrapper>
      </SettingsPaddedContainer>

      {!!customer && (
        <>
          <EditCustomerVatRateDialog
            ref={editVATDialogRef}
            customer={customer}
            appliedTaxRatesTaxesIds={customer.taxes?.map((t) => t.id)}
          />
          <EditCustomerInvoiceGracePeriodDialog
            ref={editInvoiceGracePeriodDialogRef}
            invoiceGracePeriod={customer?.invoiceGracePeriod}
          />
          <EditCustomerDunningCampaignDialog
            ref={editCustomerDunningCampaignDialogRef}
            customer={customer}
          />

          <EditCustomerIssuingDatePolicyDialog
            ref={editIssuingDatePolicyDialogRef}
            customer={customer}
          />
          <EditCustomerInvoiceCustomSectionsDialog
            ref={editCustomerInvoiceCustomSectionsDialogRef}
            customerId={customerId}
          />
          <DeleteCustomerGracePeriodeDialog ref={deleteGracePeriodDialogRef} customer={customer} />
          <EditNetPaymentTermDialog
            ref={editNetPaymentTermDialogRef}
            description={translate('text_64c7a89b6c67eb6c988980eb')}
          />
          <DeleteOrganizationNetPaymentTermDialog
            ref={deleteOrganizationNetPaymentTermDialogRef}
            customer={customer}
          />
          <EditFinalizeZeroAmountInvoiceDialog
            ref={editFinalizeZeroAmountInvoiceDialogRef}
            entity={customer}
            finalizeZeroAmountInvoice={customer?.finalizeZeroAmountInvoice}
          />
          <DeleteCustomerFinalizeZeroAmountInvoiceDialog
            ref={deleteCustomerFinalizeZeroAmountInvoiceDialogRef}
            customer={customer}
          />
        </>
      )}
    </>
  )
}
