import { CustomerMainInfosFragment, ProviderPaymentMethodsEnum } from '~/generated/graphql'

export const createMockCustomerDetails = (
  overrides: Partial<CustomerMainInfosFragment> = {},
): CustomerMainInfosFragment => {
  return {
    __typename: 'Customer',
    id: 'cust_001',
    name: 'John Doe',
    firstname: 'Jonathan',
    lastname: 'Doe',
    customerType: 'Individual',
    addressLine1: 'Via Toledo',
    addressLine2: 'Apartment 5B',
    city: 'Napoli',
    state: 'Campania',
    country: 'IT',
    zipcode: '80100',
    url: 'https://example.com',
    phone: '+390812345678',
    email: 'john.doe@example.com',
    externalId: 'EXT123',
    externalSalesforceId: 'SF123',
    legalName: 'Napoli Legal Name',
    legalNumber: '123456789',
    taxIdentificationNumber: 'IT123456789',
    currency: 'EUR',
    paymentProvider: 'stripe',
    paymentProviderCode: 'stripe',
    timezone: 'Europe/Rome',
    billingEntity: {
      __typename: 'BillingEntity',
      id: 'billing-entity-1',
      name: 'Entity 1',
      code: 'E1',
    },
    metadata: [
      { __typename: 'CustomerMetadata', id: '1', key: 'Custom Field 1', value: 'Value 1' },
      { __typename: 'CustomerMetadata', id: '2', key: 'Custom Field 2', value: 'Value 2' },
    ],
    shippingAddress: {
      __typename: 'CustomerAddress',
      addressLine1: 'Corso Umberto I',
      addressLine2: 'Building A',
      city: 'Napoli',
      state: 'Campania',
      country: 'IT',
      zipcode: '80133',
    },
    anrokCustomer: {
      __typename: 'AnrokCustomer',
      id: 'anrok_001',
      integrationId: 'AnrokIntegration',
      externalCustomerId: 'ext_anrok_001',
    },
    avalaraCustomer: {
      __typename: 'AvalaraCustomer',
      id: 'avalara_001',
      integrationId: 'AvalaraIntegration',
      externalCustomerId: 'ext_avalara_001',
    },
    netsuiteCustomer: {
      __typename: 'NetsuiteCustomer',
      id: 'netsuite_001',
      integrationId: 'NetsuiteIntegration',
      externalCustomerId: 'ext_netsuite_001',
    },
    xeroCustomer: {
      __typename: 'XeroCustomer',
      id: 'xero_001',
      integrationId: 'XeroIntegration',
      externalCustomerId: 'ext_xero_001',
    },
    hubspotCustomer: {
      __typename: 'HubspotCustomer',
      id: 'hubspot_001',
      integrationId: 'HubspotIntegration',
      externalCustomerId: 'ext_hubspot_001',
      targetedObject: 'COMPANY',
    },
    salesforceCustomer: {
      __typename: 'SalesforceCustomer',
      id: 'sf_001',
      integrationId: 'SalesforceIntegration',
      externalCustomerId: 'ext_sf_001',
    },
    providerCustomer: {
      __typename: 'ProviderCustomer',
      id: 'prov_cust_001',
      providerCustomerId: 'ProviderCustomer',
      providerPaymentMethods: [ProviderPaymentMethodsEnum.Card],
    },
    ...overrides,
  } as unknown as CustomerMainInfosFragment
}
