FROM rust:1.85 AS rust-build

RUN git clone https://github.com/getlago/lago-expression/
WORKDIR /lago-expression/expression-go
RUN git checkout v0.1.4 && cargo build --release

FROM golang:1.24 AS go-build

WORKDIR /app

RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install github.com/air-verse/air@latest

COPY --from=rust-build /lago-expression/target/release/libexpression_go.so /usr/lib/libexpression_go.so
COPY go.mod go.sum ./
RUN go mod download

# Expose the debugging port
EXPOSE 2345

CMD ["air", "-c", ".air.toml"]
